ejercicio 6

diff --git a/devops/Jenkinsfile b/devops/Jenkinsfile
--- a/devops/Jenkinsfile
+++ b/devops/Jenkinsfile
@@ -57,5 +57,27 @@ pipeline {
         }
       }
     }
+    stage('CD') {
+        steps {
+            script {
+                sh 'docker compose up -d'
+                sh 'sleep 5'
+                sh 'curl --fail http://localhost:5001'
+            }
+        }
+        post {
+            always {
+                sh 'docker compose down --volumes || true'
+                sh 'docker rmi IMAGE_NAME || true'
+            }
+            success {
+                echo 'SUCCESS'
+            }
+            failure {
+                echo 'FAILURE'
+                sh 'docker compose logs || true'
+            }
+        }
+    }
   }
 }
